### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by johnnydevs** [shameemreza/helpdesk#3]
Hi,

This looks like a great project, thanks! - is it still being supported?

I downloaded the zip file, changed the config.php values (I'm on an XAMPP setup), however I am seeing the following error messages;

```
Notice: Undefined variable: host in C:\xampp\htdocs\helpdesk2\init.php on line 8

Notice: Undefined variable: port in C:\xampp\htdocs\helpdesk2\init.php on line 9

Notice: Undefined variable: username in C:\xampp\htdocs\helpdesk2\init.php on line 10

Notice: Undefined variable: password in C:\xampp\htdocs\helpdesk2\init.php on line 11
```
It also seems that the css styling is missing.

My config.php contains the following as my URL;

`$website_url = "localhost/helpdesk2/";`

How do install the database tables and data, is this supposed to be automatic?

**Comment by shameemreza** [comment]
Make sure you used write information and also you enable write permission for files and directory while installing the scripts. I just tried in my side(xaamp) and its working as expected.

I will be happy, if you can let me know about the css. Or may be you can contribute. :)

Thanks
